# permissions for end users to view routines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routine-viewer-role
rules:
- apiGroups:
  - keydb.krestomat.io
  resources:
  - routines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keydb.krestomat.io
  resources:
  - routines/status
  verbs:
  - get
